version: "2"

##############################################
##       Docker Services Configuration      ##
##############################################

services:
  resolver:
    build:
      context: ./Resolver
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      local_net:
        ipv4_address: 172.16.0.2
    volumes:
      - ./Resolver/named.conf:/etc/bind/named.conf
    container_name: resolver

  soa-in:
    build:
      context: ./SOA-in
      dockerfile: Dockerfile
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    networks:
      local_net:
        ipv4_address: 172.16.0.3
    volumes:
      - ./SOA-in/named.conf:/etc/bind/named.conf
      - ./SOA-in/intranet.m1-5.ephec-ti.be:/etc/bind/intranet.m1-5.ephec-ti.be
      - ./SOA-in/reverse:/etc/bind/reverse
    container_name: soa-in

  database:
    build:
      context: ./Db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5000:3306"
    networks:
      local_net:
        ipv4_address: 172.16.0.5
    volumes:
      - ./Db/sql/:/data/
    environment:
      MYSQL_ROOT_PASSWORD: sysadmin
    container_name: mysql-db

  web-local:
    build:
      context: ./Web-local
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      local_net:
        ipv4_address: 172.16.0.4
    volumes:
      - ./Web-local/www/:/var/www/
      - ./Web-local/sites-available/:/etc/apache2/sites-available/
      - ./Web-local/apache2.conf:/etc/apache2/apache2.conf
    container_name: web-local

##############################################
##       Docker Networks Configuration      ##
##############################################

networks:
  local_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

  dmz_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
