
version: "3.3"

services:
    web-dmz:
        build:
            context: ./Web-dmz
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Web-dmz/www/:/var/www/
            - ./Web-dmz/sites-available/:/etc/apache2/sites-available/
            - ./Web-dmz/apache2.conf:/etc/apache2/apache2.conf
        container_name: web-dmz

    database:
        build:
            context: ./Db
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "5000:3306"
        volumes:
            - ./Db/sql/:/data/
        environment:
            MYSQL_ROOT_PASSWORD: admin
        container_name: mysql-db
